import type { Metadata } from "next";
import { AuthProvider } from "../components/providers/auth-provider";
import { NotificationProvider } from "../components/providers/notification-provider";
import { DatabaseProvider } from "../components/providers/database-provider";
import localFont from "next/font/local";
import "../styles/globals.css";

const geistSans = localFont({
  src: "../../public/fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});

const geistMono = localFont({
  src: "../../public/fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const timesNewRoman = localFont({
  src: "../../public/fonts/TimesNewRoman.woff",
  variable: "--font-times-new-roman",
  weight: "100 900",
});

const jetbrainsMono = localFont({
  src: "../../public/fonts/JetBrainsMonoNerdFont-Medium.ttf",
  variable: "--font-nerd-jetbrains",
  weight: "100 900",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${timesNewRoman.variable} antialiased`}
      >
        <NotificationProvider>
          <DatabaseProvider>
            <AuthProvider>
              {children}
            </AuthProvider>
          </DatabaseProvider>
        </NotificationProvider>
      </body>
    </html>
  );
}
